from pydantic import BaseModel
# 2. Class which describes Bank Notes measurements
class Preferences(BaseModel):
        k:int=5
        Action:float
        Adventure:float
        Cars:float
        Comedy:float
        Dementia:float
        Demons:float
        Drama:float
        Ecchi:float
        Fantasy:float
        Game:float
        Harem:float
        Hentai:float
        Historical:float
        Horror:float
        Josei:float
        Kids:float
        Magic:float
        Martial_Arts:float
        Mecha:float
        Military:float
        Music:float
        Mystery:float
        Parody:float
        Police:float
        Psychological:float
        Romance:float
        Samurai:float
        School:float
        Sci_Fi:float
        Seinen:float
        Shoujo:float
        Shoujo_Ai:float
        Shounen:float
        Shounen_Ai:float
        Slice_of_Life:float
        Space:float
        Sports:float
        Super_Power:float
        Supernatural:float
        Thriller:float
        Vampire:float
        Yaoi:float
        Yuri:float